ingress:
  enabled: true
  hosts: [grafana.malumn.local]
  ingressClassName: nginx  

adminUser: logadmin
adminPassword: todo

# datasources:
#   datasources.yaml:
#     apiVersion: 1
#     datasources:
#     - name: Loki
#       type: loki
#       url: http://loki.loki.svc.cluster.local:3100
#       jsonData:
#         httpHeaderName1: 'X-Scope-OrgID'
#       secureJsonData:
#         httpHeaderValue1: '1'