apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: malumnweb-hpa
spec:
  maxReplicas: 12
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: malumnweb-deploy
  targetCPUUtilizationPercentage: 50