apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: malumnweb-app

commonLabels:
  cluster: dmz 
  app: malumnweb-app

resources:
  - namespace.yaml
  - configMap.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - ingress.yaml
  - networkPolicy.yaml
  - Issuer.yaml
  - hpa.yaml
