apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmChartInflationGenerator:
  - chartName: prometheus
    chartRepoUrl: https://prometheus-community.github.io/helm-charts
    chartVersion: 21.1.1
    releaseName: monitoring
    values: values.yaml
    