apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

commonLabels:
  cluster: internal 
  app: ingress

resources:
  - namespace.yaml

helmChartInflationGenerator:
  - chartName: ingress-nginx
    chartRepoUrl: https://kubernetes.github.io/ingress-nginx
    chartVersion: 4.6.0
    releaseName: ingress-nginx
    values: values.yaml