apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intranet-app

commonLabels:
  cluster: internal 
  app: intranet-app

resources:
  - namespace.yaml
  - deployment.yaml
  - svc.yaml
  - ingress.yaml
  - configMap.yaml
  - networkPolicy.yaml