apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

commonLabels:
  cluster: internal 
  app: metrics-server

helmChartInflationGenerator:
  - chartName: metrics-server
    chartRepoUrl: https://kubernetes-sigs.github.io/metrics-server/
    chartVersion: 3.10.0
    releaseName: metrics-server
    values: values.yaml