apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash
spec:
  type: LoadBalancer
  loadBalancerIP: 10.20.0.52
  ports:
    - name: "syslog-udp"
      port: 1514
      protocol: UDP
      targetPort: 1514
  selector:
    app.kubernetes.io/name: eck-logstash
    app.kubernetes.io/component: logstash