adminUser: ENC[AES256_GCM,data:Pyx5y28=,iv:7T55aautoqDAno8Ew73DXi2+OMYhs/sjw1+B+7zENV0=,tag:l/DGYLYDnL3WAvXxGriD6w==,type:str]
adminPassword: ENC[AES256_GCM,data:lY1312Hqw3g/MOaFeXwHuMdUMijiLjlkYT8=,iv:IkuMfIA48kJ5bQAsYB9UJ33A7foMZg/DpbmN2qiABUU=,tag:0OQpSvkLrvvMkQKRVArWuQ==,type:str]
persistence:
    enabled: ENC[AES256_GCM,data:57fLOg==,iv:Vtinigj4USaoVneebpFNHkUyBUIS40FSGhwX0x43jHw=,tag:aOEzuvsDeB47A6muM6IO+Q==,type:bool]
ingress:
    enabled: ENC[AES256_GCM,data:Kw7PLA==,iv:WHnK81m/EWO1RStKFalXG4N1liPG7S1EJY/O6wcG3yI=,tag:4bq7ao8ZFWhBcWss7lo4MQ==,type:bool]
    hosts:
        - ENC[AES256_GCM,data:l9igxPGfpbAdDUSs28rvkuyHF8Y=,iv:/O4y36CICHcybfu/7JD2JWvbXFrsYwfeCzlRViUp4/k=,tag:ao3XS5kwun1lHYcZ14Bo4A==,type:str]
    ingressClassName: ENC[AES256_GCM,data:NoReG30=,iv:MmdL2WRVaNforFlsWfoovfkKbRgj1+eLsKg4RlEHOqw=,tag:9sm4M0nNEBp9SuiAHw37xw==,type:str]
datasources:
    datasources.yaml:
        apiVersion: ENC[AES256_GCM,data:Vg==,iv:olfYBVkb1ozU0Hdq65hBEUba4ZVPcOISepgD03cqaas=,tag:38YmMKgnT/pdbjQtgokjHQ==,type:int]
        datasources:
            - name: ENC[AES256_GCM,data:ppSJ4TnhmQzjZOVL/McnM56AXw==,iv:wRXqdSeRdF3JKK++FSRJYhukwoDA4FIiZvMLrYzUYG0=,tag:RSO5/nRBuKl2cgsOnr9mzw==,type:str]
              type: ENC[AES256_GCM,data:NDxSB45MKxDbBg==,iv:86/WUk3ajHDxQ3cQEA8SRgg7NBXVjPEtnWtL/TrUgoA=,tag:fUiQFSyDjxxqZ8kfIrqDjQ==,type:str]
              url: ENC[AES256_GCM,data:RSiqbWeGGQYovu24yKyDFtbLtr76/KsgNaFXp2iRUkNiOhA=,iv:kg3NqF2pZTvD9LA9P8moWaetSyleYgZs7/gZGCCKOyw=,tag:8GoGMTbLL1tFdYZ/HUKLEA==,type:str]
              access: ENC[AES256_GCM,data:LXXtXuU=,iv:FrZJm1/HCTifaRPzqiBuC6+wk3AWoKJnPilI/8pFDQs=,tag:mfdHr677vn37HVQF90EoZQ==,type:str]
              isDefault: ENC[AES256_GCM,data:qKzqgw==,iv:UcNWajj+hKekAgP8npvm1WxTxYZgsqHQevTnCUkMOJE=,tag:pKG1kJQSSCtwwHxxjP4WOA==,type:bool]
            - name: ENC[AES256_GCM,data:p7Q50VE5DuAND9M/S28=,iv:7oXmcnB0YFqJWTlf4CyZrI3FcmdJUCJxtNoarGrnmxg=,tag:Uh+NtINpeWbZC765WJqJxA==,type:str]
              type: ENC[AES256_GCM,data:Dxb2D6IcZ7hM7A==,iv:qhSngxsFFJF+SjI27jrifHLZnQQeoLT2jTMQ26bH1vY=,tag:bLMCR3aVXTL8kQMlr93fjA==,type:str]
              url: ENC[AES256_GCM,data:oIQ8MiURsPuUmAaAB8yAhD9SnE+ES0x+mj10ckewfw==,iv:lWvH+y8LPHN/PTsU//Po8bI2F2SVEn3KH5p8wqkdYNk=,tag:7dP2CKuRClZsnNb1LpQTEA==,type:str]
              access: ENC[AES256_GCM,data:YCATCao=,iv:m1rwwDTwQ0xUiAvJtIltAHiCsJ3Uzr9M7O4C412ko0M=,tag:nvtc7JzvRhccjfuHbQSDBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10fzf64cwmwfe8lx7n4fx3fc9d3y6k09mmt6rye40nd7jz2z5uuss6gzg8h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OWhGNVJCWVV5b0NkN1Nh
            MFVqYlFpOTV1NjJDWGZxSGpZNGYwVHNSaHlRClFCcFIvNDJLZGZya2VGb2ZaNElr
            TjRrUFRiUVpHVjMxODYyaUVPZDE4Y1EKLS0tIEU3dlBBMVM3WnBwd2E2UXhGZjBB
            Szhab3dncUdKYkNRanNQYlhiVldSbHcKPY+pffcDr3nxFo1OBpK71JRXFKuNRGob
            x+d7bG5AxJteyP9jd+4k8M0T6demf4uElu0tqtTUhmy8Jc/CG3bzmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-01T14:23:36Z"
    mac: ENC[AES256_GCM,data:cvaXIdoN3+wjUW55pRyzqSWB3QdMvgT3uhDRSHiErv3Gteynu3Tpr3LjuzlPWcOKpOmll75yqqsXwYfktNlJBorP/qneXhXfAe0AG79x3S5nkeNfWQMenWWeMFy0yY8uC0Q74e0BZuEdtu87C2N8Wxtydp5RIjJCxPB/sLeFLvg=,iv:ZZLwyQjmgqaE8bFtZZpkOmWZUXtFEDJFUSwcCR+rCzI=,tag:Z3gdMbMsy9agsepCpWfOLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
