apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-mananger

commonLabels:
  cluster: dmz 
  app: cert-mananger

resources:
  - namespace.yaml

helmChartInflationGenerator:
  - chartName: cert-manager
    chartRepoUrl: https://charts.jetstack.io
    chartVersion: v1.11.0
    releaseName: cert-manager
    values: values.yaml