apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: main
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: main
  http:
    tls:
      selfSignedCertificate:
        disabled: true