apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: filebeat

resources:
  - namespace.yaml
  - secret.yaml

helmChartInflationGenerator:
  - chartName: filebeat
    chartRepoUrl: https://helm.elastic.co
    chartVersion: 8.5.1
    releaseName: filebeat
    values: values.yaml
    